---
title: "328t_final_proj"
author: "Victoria Stavish"
date: "2022-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libraries

```{r}

library(tidyverse)
library(dplyr)
library(writexl)
library(janitor)
library(readxl)
library(openxlsx)

```

# load data 

```{r}

data <- read_excel("salary_2022.xlsx")

```

# filterfor all positions across all schools

```{r}

all_positions <- data %>%
  clean_names() %>%
  select(division, category_status, category_status_cd, appt_base_annual_salary) %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(!str_detect("VP Research|Graduate School|Undergraduate Studies| Office of the President|Sr VP Academic Affairs & Provost|VP Student Affairs|Universities at Shady Grove|Office of Extended Studies|Libraries", division)) 

median_total <- median(all_positions$appt_base_annual_salary)

write.xlsx(all_positions, file = 'C:/Users/Vstav/OneDrive/Documents/GitHub/328t/final_proj/salary_data.xlsx')

all_positions_count <- data %>%
  clean_names() %>%
  group_by(primary_name) %>%
  count()

all_positions <- all_positions %>%
  

```

# separated by division

```{r}

engineering <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "A. James Clark School of Engineering") 

cmns <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Computer, Math & Natural Sciences") 

agr <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Agriculture & Natural Resources") 

arhu <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Arts & Humanities") 

bsos <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Behavioral & Social Sciences") 

education <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Education") 

infosci <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Information Studies") 

jour <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Philip Merrill College of Journalism")  

business <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Robert H. Smith School of Business") 

arch <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Architecture, Planning, & Preservation")  

sph <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Public Health")

policy <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Public Policy") 

all_divs <- list('Sheet1' = engineering, 'Sheet2' = cmns, 'Sheet3' = agr, 'Sheet4' = arhu, 'Sheet5' = bsos, 'Sheet6' = education, 'Sheet7' = infosci, 'Sheet8' = jour, 'Sheet9' = business, 'Sheet10' = arch, 'Sheet11' = sph, 'Sheet12' = policy)
write.xlsx(all_divs, file = 'C:/Users/Vstav/OneDrive/Documents/GitHub/328t/final_proj/salary_by_division.xlsx')

```

# number of faculty in each division

```{r}

count_engineering <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "A. James Clark School of Engineering") %>%
  group_by(primary_name) %>%
  count()

count_cmns <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Computer, Math & Natural Sciences") %>%
  group_by(primary_name) %>%
  count()

count_agr <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Agriculture & Natural Resources") %>%
  group_by(primary_name) %>%
  count()

count_arhu <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Arts & Humanities") %>%
  group_by(primary_name) %>%
  count()

count_bsos <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Behavioral & Social Sciences") %>%
  group_by(primary_name) %>%
  count()

count_education <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Education") %>%
  group_by(primary_name) %>%
  count()

count_infosci <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Information Studies") %>%
  group_by(primary_name) %>%
  count()

count_jour <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Philip Merrill College of Journalism")%>%
  group_by(primary_name) %>%
  count()

count_business <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Robert H. Smith School of Business") %>%
  group_by(primary_name) %>%
  count()

count_arch <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Architecture, Planning, & Preservation")%>%
  group_by(primary_name) %>%
  count()

count_sph <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Public Health")%>%
  group_by(primary_name) %>%
  count()

count_policy <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Public Policy")%>%
  group_by(primary_name) %>%
  count()
  

```

# overall median salaries

```{r}

median_business <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Robert H. Smith School of Business")


  median_business <- median(median_business$appt_base_annual_salary)
  
median_engineering <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "A. James Clark School of Engineering")

median_engineering <- median(median_engineering$appt_base_annual_salary)

median_cmns <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Computer, Math & Natural Sciences") 

median_cmns <- median(median_cmns$appt_base_annual_salary)

median_agr <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Agriculture & Natural Resources") 

median_agr <- median(median_agr$appt_base_annual_salary)

median_arhu <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Arts & Humanities") 

median_arhu <- median(median_arhu$appt_base_annual_salary)

median_bsos <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Behavioral & Social Sciences") 

median_bsos <- median(median_bsos$appt_base_annual_salary)

median_education <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Education") 

median_education <- median(median_education$appt_base_annual_salary)

median_infosci <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Information Studies") 

median_infosci <- median(median_infosci$appt_base_annual_salary)

median_jour <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Philip Merrill College of Journalism")  

median_jour <- median(median_jour$appt_base_annual_salary)

median_arch <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Architecture, Planning, & Preservation")  

median_arch <- median(median_arch$appt_base_annual_salary)

median_sph <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Public Health")

median_sph <- median(median_sph$appt_base_annual_salary)

median_policy <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Public Policy")

median_policy <- median(median_policy$appt_base_annual_salary)

```

# overall min salaries

```{r}

min_business <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Robert H. Smith School of Business")%>%
  slice_min(appt_base_annual_salary, n = 1)

min_engineering <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "A. James Clark School of Engineering") %>%
  slice_min(appt_base_annual_salary, n = 1)

min_cmns <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Computer, Math & Natural Sciences")%>%
  slice_min(appt_base_annual_salary, n = 1) 

min_agr <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Agriculture & Natural Resources") %>%
  slice_min(appt_base_annual_salary, n = 1)

min_arhu <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Arts & Humanities") %>%
  slice_min(appt_base_annual_salary, n = 1)

min_bsos <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Behavioral & Social Sciences") %>%
  slice_min(appt_base_annual_salary, n = 1)

min_education <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Education") %>%
  slice_min(appt_base_annual_salary, n = 1)

min_infosci <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "College of Information Studies") %>%
  slice_min(appt_base_annual_salary, n = 1)

min_jour <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Philip Merrill College of Journalism") %>%
  slice_min(appt_base_annual_salary, n = 1) 

min_business <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "Robert H. Smith School of Business") %>%
  slice_min(appt_base_annual_salary, n = 1)

min_arch <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Architecture, Planning, & Preservation")%>%
  slice_min(appt_base_annual_salary, n = 1)

min_sph <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Public Health")%>%
  slice_min(appt_base_annual_salary, n = 1)

min_policy <- data %>%
  as.data.frame() %>%
  clean_names() %>%
  filter(grepl("Tenured Faculty|Tenure Track Faculty|Non-Tenured,Cont. Contr. Faculty|Non-Tenured, Term. Contr. Faculty|Non-Tenured, Non-Regular Faculty", category_status)) %>%
  filter(division == "School of Public Policy") %>%
  slice_min(appt_base_annual_salary, n = 1)

```







